apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neox
spec:
  replicas: 4
  serviceName: neox
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: neox
  template:
    metadata:
      labels:
        app: neox
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: neox
        tty: true
        image: leogao2/gpt-neox
        ports:
          - name: sshd
            containerPort: 22
            protocol: TCP
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - name: secret-volume
            readOnly: true
            mountPath: "/secrets"
          - name: data-storage
            mountPath: /mnt/ssd-0
            readOnly: true
          - name: cluster-storage
            mountPath: /mnt/ssd-cluster
            readOnly: false
        resources:
          requests:
            cpu: "100"
            memory: 700Gi
            nvidia.com/gpu: "6"
          limits:
            nvidia.com/gpu: "6"
        lifecycle:
          postStart:
            exec:
              command: [ "/bin/bash", "/secrets/post_start_script.sh" ]

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu.nvidia.com/model
                operator: In
                values:
                  - A100_PCIE_40GB
                  - A100-PCIE-40GB
              - key: failure-domain.beta.kubernetes.io/region
                operator: In
                values:
                  - ORD1
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: secret-volume
          secret:
            secretName: ----secret-name----
            defaultMode: 0777
        - name: data-storage
          persistentVolumeClaim:
            claimName: eleuther-ssd-0
            readOnly: true
        - name: cluster-storage
          persistentVolumeClaim:
            claimName: eleuther-ssd-cluster
            readOnly: false
      restartPolicy: Always
