{
   "model-parallel-size":1,
   "pipe-parallel-size":2,
   "num-layers":24,
   "hidden-size":2048,
   "num-attention-heads":16,
   "seq-length":1024,
   "max-position-embeddings":1024,
   "batch-size":4,
   "gradient_accumulation_steps":16,
   "train-iters":320000,
   "lr-decay-iters":320000,
   "save":"checkpoints/gpt2_XL_ds",
   "load":"checkpoints/gpt2_XL_ds",
   "data-impl":"mmap",
   "split":"949,50,1",
   "distributed-backend":"nccl",
   "lr":0.0002,
   "lr-decay-style":"cosine",
   "min-lr":2e-05,
   "weight-decay":0,
   "attention-dropout":0,
   "hidden-dropout":0,
   "clip-grad":1.0,
   "warmup":0.01,
   "checkpoint-activations":true,
   "log-interval":1,
   "save-interval":500,
   "eval-interval":100,
   "eval-iters":10,
   "fp16":{
      "enabled":true,
      "loss_scale":0,
      "loss_scale_window":1000,
      "hysteresis":2,
      "min_loss_scale":1
   },
   "tensorboard-dir":"tensorboard_data/l_h_1n_8g_2pp_1mp_4b_ds4",
   "sparsity":"interspersed",
   "deepspeed":true,
   "zero-stage":1,
   "zero-reduce-bucket-size":50000000,
   "zero-allgather-bucket-size":5000000000,
   "zero-contigious-gradients":true,
   "zero-reduce-scatter":true,
   "checkpoint-num-layers":1,
   "partition-activations":true,
   "checkpoint-in-cpu":true,
   "synchronize-each-layer":true,
   "train_micro_batch_size_per_gpu":4,
   "steps_per_print":10,
   "zero_optimization":{
      "stage":1,
      "allgather_partitions":true,
      "reduce_scatter":true,
      "allgather_bucket_size":50000000,
      "reduce_bucket_size":50000000,
      "overlap_comm":true
   },
   "optimizer":{
      "type":"Adam",
      "params":{
         "lr":0.00015,
         "max_grad_norm":1.0,
         "betas":[
            0.9,
            0.95
         ]
      }
   },
   "gradient_clipping":1.0,
   "wall_clock_breakdown":true,
   "zero_allow_untested_optimizer":false
}