{
#   "num_nodes": 1,
#   "num_gpus": 8,
   "model-parallel-size": 4,

   "num-layers": 24,
   "hidden-size": 1024,
   "num-attention-heads": 15,
   "seq-length": 1024,
   "max-position-embeddings": 1024,

   "train-iters": 320000,
   "lr-decay-iters": 320000,
   "save": "checkpoints/gpt2_345m_ds",
   "load": "checkpoints/gpt2_345m_ds",
   "data-impl": "mmap",
   "split": "949,50,1",
   "distributed-backend": "nccl",
   "lr": 1.5e-4,
   "lr-decay-style": "cosine",
   "min-lr": 1.0e-5,
   "weight-decay": 1e-2,
   "clip-grad": 1.0,
   "warmup": 0.01,

   "checkpoint-activations": true,
   "log-interval": 100,
   "save-interval": 10000,
   "eval-interval": 1000,
   "eval-iters": 10,
   "tensorboard-dir": "tensorboard_data/24l_1024h_1n_8g_4mp_9b_ds4",
   "deepspeed": true,

   "zero-stage": 0,
   "zero-reduce-bucket-size": 50000000,
   "zero-allgather-bucket-size": 5000000000,
   "zero-contigious-gradients": true,
   "zero-reduce-scatter": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": true,

  # Deepspeed conf ds_config.json
   "train_micro_batch_size_per_gpu": 4,
   "steps_per_print": 10,
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.00015,
       "max_grad_norm": 1.0,
       "betas": [0.9, 0.95]
     }
   },
   "gradient_clipping": 1.0,
   "fp16": { # Duplicated in megatron
     "fp16": true,
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "hysteresis": 2,
     "min_loss_scale": 1
   },
   "wall_clock_breakdown": true,
   "zero_allow_untested_optimizer": false
}
