# Data paths and options when using EleutherAI cluster
{
  "data-path": "/mnt/ssd-cluster/data/enron/enron_text_document",
  "vocab-file": "/mnt/ssd-cluster/data/gpt2-vocab.json",
  "merge-file": "/mnt/ssd-cluster/data/gpt2-merges.txt",
  "log-dir": "/mnt/ssd-cluster/logs",
  "wandb_team": "eleutherai",
}