# Suggested data paths when using GPT-NeoX locally
{
  "data-path": "data/enron/enron_text_document",
#  "train-data-path": "data/train/train_text_document",
#  "test-data-path": "data/test/test_text_document",
#  "valid-data-path": "data/valid/valid_text_document",
  "vocab-file": "data/gpt2-vocab.json",
  "merge-file": "data/gpt2-merges.txt",
  "save": "checkpoints",
  "load": "checkpoints",
  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",
  "use_wandb": True,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "neox"
}