# Suggested data paths when using GPT-NeoX locally
{
  "data-path": "data/enron/enron_text_document",
  "vocab-file": "data/gpt2-vocab.json",
  "merge-file": "data/gpt2-merges.txt",
  "save": "checkpoints",
  "load": "checkpoints",
  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",
}