# Add this to your config for sparse attention every other layer
{
  "attention_config": [[["sparse_variable", "global"], "all"]],

  # sparsity config:
  # (these are the defaults for variable sparsity, training will work without this here, but it's left in for
  # illustrative purposes)
  # see https://www.deepspeed.ai/tutorials/sparse-attention/#how-to-config-sparsity-structures for
  # more detailed config instructions and available parameters

  "sparsity_config": {
    "block": 16, # block size
    "different_layout_per_head": false,
    "num_random_blocks": 0, # 0 = no randomness
  }
}