[tool.poetry]
name = "gpt-neox-mamba"
version = "0.1.0"
description = "Mamba requirements for GPT-NeoX"
authors = ["EleutherAI <contact@eleuther.ai>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
causal_conv1d = ">=1.1.0"
einops = "*"
mamba_ssm = ">=1.2.0.post1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
