[tool.poetry]
name = "gpt-neox-dev"
version = "0.1.0"
description = "Development requirements for GPT-NeoX"
authors = ["EleutherAI <contact@eleuther.ai>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
autopep8 = ">=1.5.6"
clang-format = ">=13.0.1"
pre-commit = ">=2.17.0"
pytest = ">=6.2.3"
pytest-cov = ">=2.11.1"
pytest-forked = ">=1.3.0"
pytest-html = "4.1.1"
pytest-xdist = "*"
toml = ">=0.10.2"
packaging = ">=23.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
