[tool.poetry]
name = "gpt-neox-apex-pip"
version = "0.1.0"
description = "Apex pip requirements for GPT-NeoX"
authors = ["EleutherAI <contact@eleuther.ai>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
pip = "23.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
