[tool.poetry]
name = "gpt-neox-transformerengine"
version = "0.1.0"
description = "Transformer Engine requirements for GPT-NeoX"
authors = ["EleutherAI <contact@eleuther.ai>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
transformer-engine = {git = "https://github.com/NVIDIA/TransformerEngine.git", rev = "stable"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
